apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vela-system

resources:
- custom-webservice.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: custom-components
    app.kubernetes.io/part-of: kubevela
    managed-by: argocd
