resources:
  - envoyproxy-nodeports.yaml
  - gatewayclass.yaml

patches:
  - target:
      kind: Service
      labelSelector: gateway.envoyproxy.io/owning-gateway-name=zeus-gw
    patch: |-
      apiVersion: v1
      kind: Service
      spec:
        type: NodePort
        ports:
          - port: 80
            nodePort: 30080
          - port: 443
            nodePort: 30443
