kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: zeus

networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6334

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            # Taint the control plane node to prevent workload scheduling
            register-with-taints: "node-role.kubernetes.io/control-plane=:NoSchedule"
            cloud-provider: "external"
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "node-role.kubernetes.io/worker=true"
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "node-role.kubernetes.io/worker=true"