resources:
  - app-00-gateway-api-crds.yaml
  - app-10-envoy-gateway.yaml
  - app-30-edge.yaml
  - app-40-kubevela.yaml
  - app-50-kubevela-addons.yaml
  - app-60-kubevela-gateway.yaml
  - project-observability.yaml
  - app-70-prometheus-operator-crds.yaml
  - app-70-metrics-server.yaml
  - app-71-kube-prometheus-stack.yaml
  - app-72-opentelemetry-operator.yaml
  - app-73-observability-gateway.yaml
