apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

resources:
  - gateway.yaml
  - httproute-argocd.yaml
  - httproute-velaux.yaml

secretGenerator:
  - name: zeus-wildcard-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=certs/zeus.crt
      - tls.key=certs/zeus.key

generatorOptions:
  disableNameSuffixHash: true