apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vela-system

resources:
  - httproute-velaux.yaml
  - backendtls-velaux.yaml
  - velaux-backend-ca-secret.yaml
  - velaux-serviceaccount.yaml
  - velaux-clusterrolebinding.yaml
  - velaux-anon-clusterrolebinding.yaml
